import { app, BrowserWindow, ipcMain, shell, protocol } from 'electron';
import path from 'path';
import { BelaviaWindowHandler } from "./vendors/belavia/BelaviaWindowHandler";
import { getStoredSettings, storeSettings } from './utils-node';
import { ITicketSearchParameters } from './ITicketSearchParameters';
import { dateNowUtc, sleep } from './utils-universal';
import { controlsWindowWidth } from './constants';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const CONTROLS_WEBPACK_ENTRY: string;
declare const CONTROLS_PRELOAD_WEBPACK_ENTRY: string;

let ticketSearchParameters: ITicketSearchParameters | undefined;
let directionIndex = 0;

const currentDate = dateNowUtc();

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  // eslint-disable-line global-require
  app.quit();
}

// глобальные хендлеры

ipcMain.handle('get-settings', async (): Promise<ITicketSearchParameters> => {
  const settings = await getStoredSettings();
  return settings;
});

const createWindow = async (): Promise<void> => {
  const controlsWindow = new BrowserWindow({
    width: controlsWindowWidth,
    height: 700,
    minWidth: controlsWindowWidth,
    maxWidth: controlsWindowWidth,
    backgroundColor: '#444',
    webPreferences: {
      preload: CONTROLS_PRELOAD_WEBPACK_ENTRY
    }
  });

  console.log(`CONTROLS_WEBPACK_ENTRY: ${CONTROLS_WEBPACK_ENTRY}`)
  console.log(`CONTROLS_PRELOAD_WEBPACK_ENTRY: ${CONTROLS_PRELOAD_WEBPACK_ENTRY}`)

  // controlsWindow.webContents.openDevTools({ mode: 'detach' });
  controlsWindow.webContents.loadURL(CONTROLS_WEBPACK_ENTRY);

  const belaviaHandler = new BelaviaWindowHandler();

  // убирает синхронизацию заголовка с <title> страницы html
  controlsWindow.on('page-title-updated', (e) => {
    e.preventDefault();
  });

  ipcMain.removeHandler('on-tickets');
  ipcMain.removeHandler('search-tickets');
  ipcMain.removeHandler('search-tickets-stop');

  ipcMain.handle('search-tickets', async (_event, sp: ITicketSearchParameters) => {
    console.log(sp);

    ticketSearchParameters = sp;
    await storeSettings(ticketSearchParameters);

    currentDate.setTime(sp.dateFrom.getTime());

    const direction = ticketSearchParameters.directions[directionIndex];

    belaviaHandler.findTickets(direction.from, direction.to, currentDate, ticketSearchParameters);
  });

  ipcMain.handle('search-tickets-stop', () => {
    ticketSearchParameters = undefined;
    directionIndex = 0;
    currentDate.setTime(0);

    // очищаем страницу
    belaviaHandler.win.webContents.loadURL("data:text/html;base64," + "PCFET0NUWVBFIGh0bWw-CjxodG1sIGxhbmc9ImVuIj4KCjxoZWFkPgogIDxtZXRhIG5hbWU9ImRlc2NyaXB0aW9uIiBjb250ZW50PSJXZWJwYWdlIGRlc2NyaXB0aW9uIGdvZXMgaGVyZSIgLz4KICA8bWV0YSBjaGFyc2V0PSJ1dGYtOCI-CiAgPHRpdGxlPkNoYW5nZV9tZTwvdGl0bGU-CiAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCwgaW5pdGlhbC1zY2FsZT0xIj4KICA8bWV0YSBuYW1lPSJhdXRob3IiIGNvbnRlbnQ9IiI-CiAgPGxpbmsgcmVsPSJzdHlsZXNoZWV0IiBocmVmPSJjc3Mvc3R5bGUuY3NzIj4KICA8c2NyaXB0IHNyYz0iaHR0cDovL2NvZGUuanF1ZXJ5LmNvbS9qcXVlcnktbGF0ZXN0Lm1pbi5qcyI-PC9zY3JpcHQ-CjwvaGVhZD4KCjxib2R5PgogIAo8ZGl2IGNsYXNzPSJjb250YWluZXIiPgogIAo8L2Rpdj4KCjxzY3JpcHQ-Cjwvc2NyaXB0PgoKPC9ib2R5Pgo8L2h0bWw-");
  });

  ipcMain.handle('on-tickets', async (_event, ticketCount: number) => {
    if (ticketSearchParameters === undefined) {
      console.warn(`got event on-ticket but ticketSearchParameters is undefined`);
      return;
    }


    if (ticketCount > 0) {
      console.log(`Found tickets ${ticketCount}`);
      shell.openExternal(belaviaHandler.lastUrl)
      return;
    }

    if (directionIndex < ticketSearchParameters.directions.length - 1) {
      directionIndex++;

      const direction = ticketSearchParameters.directions[directionIndex];

      await sleep(Math.round((ticketSearchParameters.delayMax - ticketSearchParameters.delayMin) * Math.random() + ticketSearchParameters.delayMin));
      belaviaHandler.findTickets(direction.from, direction.to, currentDate, ticketSearchParameters);

      return;
    }

    // дошли до конца дат
    if (directionIndex === ticketSearchParameters.directions.length - 1) {

      directionIndex = 0;
    } else {
      directionIndex++;
    }

    currentDate.setDate(currentDate.getDate() + 1);

    const dayAfterMax = new Date(ticketSearchParameters.dateTo.getTime());
    dayAfterMax.setDate(dayAfterMax.getDate() + 1);

    if (currentDate.getTime() > dayAfterMax.getTime()) {
      console.log('start searching from the beginning', currentDate, dayAfterMax);

      directionIndex = 0;
      currentDate.setTime(ticketSearchParameters.dateFrom.getTime());
    }

    const direction = ticketSearchParameters.directions[directionIndex];
    await sleep(Math.round((ticketSearchParameters.delayMax - ticketSearchParameters.delayMin) * Math.random() + ticketSearchParameters.delayMin));
    belaviaHandler.findTickets(direction.from, direction.to, currentDate, ticketSearchParameters);
  });

  controlsWindow.maximize();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', async () => {

  const result = protocol.registerFileProtocol('webpackfile', (request, callback) => {
    const url = request.url.replace('webpackfile://', '');
    const normalizedUrl = path.normalize(url);

    console.log(`${request.url} --> ${normalizedUrl}`);

    callback({ path: normalizedUrl })
  });

  if (!result)
    throw new Error('Cannot register file protocol');

  await createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
